[#delay]
== Delay

You may want to test read timeout or slow backends. OAS stub provides
delay configuration for both entire APIs and single API.

[cols="1,1,1"]
|===
| Endpoint                                    | Query Parameter | Content-Type

| PUT /__admin/{context}/delay                | N/A             | application/json
| PUT /__admin/{context}/configurations/delay | api={apiPath}   | application/json
|===

Both endpoints have the same JSON body of the following format.

[source, json]
----
{
  "type": "fixed",
  "delay": 500
}
----

[cols="1,1,1"]
|===
| Option | Description | Example value

| type | Specifies delay type | `"fixed"`
| delay | Specifies delay     | `500`
| delayUnit | Unit for the `delay` | `"MILLISECONDS"`
|===

=== Delay and latency

Delay and latency configuration have similar effect to OAS stub,
the difference between them is that delay configuration delays the
response whilst latency configuration emits response slowly.
This means, delay is suitable for read timeout tests and
latency is suitable for others.
