[#getting-started]
== Getting started

:latest-is-greatest: footnote:[Use the latest version, you can check on Maven central :)]
To start building your own stub application, your first step is
to add the below dependency into your `pom.xml`.{latest-is-greatest}
We also assume, you are using Java 17 or later. OAS stub is built
atop Java 17 toolchain, so if you are using Java 11, then you need
to upgrade the JDK version.

[source, xml]
----
<dependency>
    <groupId>io.github.ktakashi.oas.stub</groupId>
    <artifactId>oas-stub-server</artifactId>
    <version>${oas-stub.version}</version>
</dependency>
----

Then you can write a very simple OAS Stub server like this:

[source, java]
----
import io.github.ktakashi.oas.server.options.OasStubOptions;
import io.github.ktakashi.oas.server.OasStubServer;

public class Main {
    public static void main(String... args) {
        var options = OasStubOptions.builder().build();
        new OasStubServer(options).start();
        Thread.currentThread().join(); // wait forever
    }
}
----

Now, you are ready to upload your OAS file to the application.
The easiest way to do it is using the above Swagger UI. If you
want to automate the process, then below shows an example how to
do it with `curl`.

[source, shell]
----
 curl -X POST http://localhost:8080/__admin/petstore \
  -H'Content-Type: application/octet-stream' \
  --data-binary @{oas_file}
----

Suppose, you've uploaded a `petstore.yaml` from the OAS example,
then you can get pets from the `GET /v1/pets` endpoint like this:

[source, shell]
----
curl http://localhost:8080/oas/petstore/v1/pets
----

Then you'll receive a JSON array with default value.

TIP: The request against the API is validated unless specified not to do by you.
