[#getting-started]
== Getting started

:latest-is-greatest: footnote:[Use the latest version, you can check on Maven central :)]
To start building your own stub application, your first step is
to add the below dependency into your `pom.xml`.{latest-is-greatest}
We also assume, you are using Java 17 or later. OAS stub is built
atop Java 17 toolchain, so if you are using Java 11, then you need
to upgrade the JDK version.

[source,xml]
----
<dependency>
    <groupId>io.github.ktakashi.oas.stub.spring</groupId>
    <artifactId>oas-stub-spring</artifactId>
    <version>${oas-stub.version}</version>
</dependency>
----

:spring-boot: footnote:[https://spring.io/projects/spring-boot]
:todo-list: footnote:[We are planning to make pure JEE web application by using Guice]
:for-now: footnote:[For now, please check `oas-stub-engine` and `oas-stub-spring` to grab how to do it]

To make our lives easier, we assume that you are using
Spring Boot{spring-boot}. If you are using other DI library
or prefer not to use Spring Boot, then you need to do it by
your self.{todo-list}{for-now}

After you added the dependency on your Spring Boot application,
then you need to add `OasApplication` to be loaded into your
application context. Below example shows how to do it:

[source, java]
----
package oas.example;

@SpringBootApplication
public class ExampleApplication {
    public static void main(String[] args) {
        SpringApplication.run(new Class[] { ExampleApplication.class, OasApplication.class }, args);
    }
}
----

To build a standalone jar file, you need to add the below `<build>`
section to your `pom.xml`.

[source, xml]
----
<build>
    <finalName>oas-stub-example</finalName>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <executions>
                <execution>
                    <goals>
                        <goal>repackage</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <classifier>dist</classifier>
                <mainClass>oas.example.ExampleApplication</mainClass>
            </configuration>
        </plugin>
    </plugins>
</build>
----

After you build the application, then you'll see
`oas-stub-example-dist.jar` in `target/` directory. The jar file
is an executable, so you can simply run like this:

[source, shell]
----
java -jar ./target/oas-stub-example-dist.jar
----

The application provides Swagger UI for its admin endpoints.
The URL of the above command's UI is
`http://localhost:8080/swagger-ui.html`. If the application is
deployed on a server, then adjust the scheme, host and port.

Now, you are ready to upload your OAS file to the application.
The easiest way to do it is using the above Swagger UI. If you
want to automate the process, then below shows an example how to
do it with `curl`.

[source, shell]
----
 curl -X POST http://localhost:8080/__admin/petstore \
  -H'Content-Type: application/octet-stream' \
  --data-binary @{oas_file}
----

Suppose, you've uploaded a `petstore.yaml` from the OAS example,
then you can get pets from the `GET /v1/pets` endpoint like this:

[source, shell]
----
curl http://localhost:8080/oas/petstore/v1/pets
----

Then you'll receive a JSON array with default value.
