[#getting-started]
== Getting started

:latest-is-greatest: footnote:[Use the latest version, you can check on Maven central :)]
To start building your own stub application, your first step is
to add the below dependency into your `pom.xml`.{latest-is-greatest}
We also assume, you are using Java 17 or later. OAS stub is built
atop Java 17 toolchain, so if you are using Java 11, then you need
to upgrade the JDK version.

:spring-boot: footnote:[https://spring.io/projects/spring-boot]
:guice: footnote:[https://github.com/google/guice]

OAS stub provides two flavours of the DI implementations. One is
Spring Boot{spring-boot} the other one is Guice{guice}. Below sections
describe how to use them.

=== Spring Boot{spring-boot}

To start with Spring Boot implementation, you need to add the
`oas-stub-spring-boot-starter-web` artifact into your `pom.xml`
like below.

[source,xml]
----
<dependency>
    <groupId>io.github.ktakashi.oas.stub.spring</groupId>
    <artifactId>oas-stub-spring-boot-starter-web</artifactId>
    <version>${oas-stub.version}</version>
</dependency>
----

Adding the above dependency enables autoconfiguration of the
OAS stub. The rest of the work you need to do is executing the
application, like the below example. (`import` clauses are omitted)

[source, java]
----
package oas.example.spring;

@SpringBootApplication
public class ExampleApplication {
    public static void main(String[] args) {
        SpringApplication.run(ExampleApplication.class, args);
    }
}
----

To build a standalone jar file, you need to add the below `<build>`
section to your `pom.xml`.

[source,xml]
----
<build>
    <finalName>oas-stub-example</finalName>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
            <executions>
                <execution>
                    <goals>
                        <goal>repackage</goal>
                    </goals>
                </execution>
            </executions>
            <configuration>
                <classifier>dist</classifier>
                <mainClass>oas.example.spring.ExampleApplication</mainClass>
            </configuration>
        </plugin>
    </plugins>
</build>
----

After you build the application, then you'll see
`oas-stub-example-dist.jar` in `target/` directory. The jar file
is an executable, so you can simply run like this:

[source, shell]
----
java -jar ./target/oas-stub-example-dist.jar
----

The application provides Swagger UI for its admin endpoints.
The URL of the above command's UI is
`http://localhost:8080/swagger-ui.html`. If the application is
deployed on a server, then adjust the scheme, host and port.

Now, you are ready to upload your OAS file to the application.
The easiest way to do it is using the above Swagger UI. If you
want to automate the process, then below shows an example how to
do it with `curl`.

[source, shell]
----
 curl -X POST http://localhost:8080/__admin/petstore \
  -H'Content-Type: application/octet-stream' \
  --data-binary @{oas_file}
----

Suppose, you've uploaded a `petstore.yaml` from the OAS example,
then you can get pets from the `GET /v1/pets` endpoint like this:

[source, shell]
----
curl http://localhost:8080/oas/petstore/v1/pets
----

Then you'll receive a JSON array with default value.

TIP: The request against the API is validated unless specified not to do by you.

=== Guice

To start with Guice implementation, you need to add the
`oas-stub-guice-module` artifact into your `pom.xml`
like below.

[source,xml]
----
<dependency>
    <groupId>io.github.ktakashi.oas.stub.guice</groupId>
    <artifactId>oas-stub-guice-module</artifactId>
    <version>${oas-stub.version}</version>
</dependency>
----

The below example is the minimum implementation of the OAS stub
server on top of Guice. (`import` clauses are omitted)

[source, java]
----
package oas.example.guice;

public class Main {
    public static void main(String[] args) {
        var configuration = OasStubGuiceServerConfiguration
                .builder()
                .build();
        var injector = OasStubGuiceInjectors.createServerInjector(configuration);
        var server = injector.getInstance(OasStubServer.class);
        server.start();
    }
}
----

If you want to make an executable jar, then you need to build
a fat jar.

The running server provides the same endpoint as the Spring Boot
version. You can use the same `curl` commands to upload the OAS
specification and others.

=== Which one to use

Both implementation have pros and cons. Here you can find some
of them.

.Spring Boot
****
.Pros

* Easy to add custom endpoints
* Easy to configure other components, such as `ObjectMapper`

.Cons

* Mixing up beans with other application
* Using the same port
* Slow start up
****

.Guice
****
.Pros

* Standalone server
* Beans won't be mixed between other DI, e.g. Spring Boot application

.Cons

* Needs a bit more effort to make custom endpoints
* Limited configuration of other components
****

In my personal opinion, Guice server is suitable for testing during
build, and Spring Boot is suitable for deployment.


