[#testing]
== Testing module

If you are using `spring-boot-starter-test` module, and considering
to use OAS stub for testing, you can easily integrate your tests
with `oas-stub-spring-boot-starter-test` or `oas-stub-spring-stub-server`
module.

=== `oas-stub-spring-boot-starter-test` module

.Module
[source, xml]
----
<dependency>
    <groupId>io.github.ktakashi.oas.stub.spring</groupId>
    <artifactId>oas-stub-spring-boot-starter-test</artifactId>
    <version>${oas-stub.version}</version>
    <scope>test</scope>
</dependency>
----

[WARNING]
====
This module requires a server, which means your test
module must not use `SpringBootTest.WebEnvironment.MOCK` or
`SpringBootTest.WebEnvironment.NONE`.
====

=== Basic usage

Suppose you have a Spring Boot application in `oas.example` package.
Now you want to test it. So, your Spring Boot test should look like
this:

[source, java]
----
package ors.example;
// imports...
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureOasStub
class ExampleApplicationTest {
    @Value("${local.server.port}")
    private int localPort;

    @Autowired
    private OasStubTestService oasStubTestService;

    @Test
    void test() {
        // HTTP access `http://localhost:${localPort}`
    }
}
----

TIP: `@EnableAutoConfiguration` is required to make it work.
This is because `oas-stub-spring-boot-starter-test` is based
on `oas-stub-spring-boot-web` and this module is a bundle of
autoconfiguration modules.

`OasStubTestService` is a convenient service for testing, which
provides API creation and validation methods. For more detail,
see the Javadoc.

=== `oas-stub-spring-stub-server` module

.Module
[source, xml]
----
<dependency>
    <groupId>io.github.ktakashi.oas.stub.spring</groupId>
    <artifactId>oas-stub-spring-stub-server</artifactId>
    <version>${oas-stub.version}</version>
    <scope>test</scope>
</dependency>
----

[NOTE]
====
The `oas-stub-spring-stub-server` requires Jetty version of `12`, this
means the default Spring Boot dependency doesn't work due to the significant
API changes on Jetty 12.
====

[WARNING]
====
If your application doesn't use bundled Jetty, such as embedded Jetty server,
then you just need to update the Jetty version. Otherwise, this module doesn't
work.
====

After you added the dependency, then you need to add `@AutoConfigureOasStubServer`
annotation to your Spring Boot test.

[source, java]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureOasStubServer
class ExampleApplicationTest {
    @Value("${local.server.port}")
    private int localPort;

    @Autowired
    private OasStubTestService oasStubTestService;

    @Test
    void test() {
        // HTTP access `http://localhost:${localPort}`
    }
}
----

[WARNING]
====
If you, for some reason, put both modules into the classpath, then the
Spring Boot will process the listeners defined in both modules. This
causes OAS stub server start up failure. To avoid it, you need to put
`oas.stub.test.server.shared` configuration to `true`.
====

=== Configurations

After you set up the basic test application, then you need to
add the `oas.stub.test` configuration to your configuration
file, such as application.yaml or application.properties. Below
example shows how to configure the petstore.

Example configuration:
[source, yaml]
----
oas.stub:
  test:
    definitions:
      petstore:
        # Spring Resource class
        specification: 'classpath:/schema/petstore.yaml'
        configurations:
          # API path, can be URI template
          '[/v1/pets/{id}]':
            data:
              # Request URI, must be a valid URI
              '[/v1/pets/1]':
                status: 200
                # Response content, can be classpath:{path}
                response: 'classpath:/json/pet1.json'
              '[/v1/pets/2]':
                status: 200
                # or raw content (string), won't be normalized
                response: |
                  { "id": 2, "name": "Pochi" }
              # Default response, when the request does not match above URIs
              default:
                status: 404
                response: 'classpath:/json/404.json'
          '[/v1/pets]':
            data:
              default:
                status: 200
                response: 'classpath:/json/pets.json'
----

Now you need to set up your backend service connection.
Suppose you have a map of backend service URI in your
configuration properties. And one of the key is `uri`.
To access OAS stub test server, you can put your backend
service like this:

[source, yaml]
----
services:
  petstore:
    uri: http://localhost:${oas.stub.test.server.port}/oas/petstore
----

TIP: The context path `/oas` can be configured with
`oas.stub.servlet.prefix`

TIP: `/\__admin/\{endpoint}` endpoints are also loaded into the
server, so users can create/modify API definitions via the REST endpoints. The endpoints will be
`http://localhost:${oas.stub.test.server.port}/__admin/\{endpoint}`

TIP: `/__admin` can be configured with `oas.stub.servlet.admin-prefix`.

For the working example, please refer test directory of the
https://github.com/ktakashi/oas-stub/tree/main/examples/petstore-broker[petstore-broker]
example.

=== Which testing module to use?

Most of the case, you should use `oas-stub-spring-stub-server` module
for testing. Using this module allow users not to share the port between
the testing application and stub server.

If you need custom stub endpoints, then `oas-stub-spring-boot-starter-test`
might be the easiest solution. But be aware that, this module requires
embedded tomcat provided by Spring Boot, which means, if your application
is desired to be run on Netty, then the module may not work properly or
you need to change the setup during testing.
