management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true

spring:
  jackson:
    default-property-inclusion: non_null
