on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:
    name: Build OAS Stub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.0
      - name: Build
        run: ./gradlew build -x test
      - name: Run tests
        run: ./gradlew test
