on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:
    name: Build OAS Stub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.0
      - name: Build
        run: ./gradlew build -x test
      - name: Run tests
        run: ./gradlew test -i
        env:
          JAVA_OPTS: |
            --add-modules java.se
            --add-exports java.base/jdk.internal.ref=ALL-UNNAMED 
            --add-opens java.base/java.lang=ALL-UNNAMED
            --add-opens java.base/sun.nio.ch=ALL-UNNAMED
            --add-opens java.management/sun.management=ALL-UNNAMED
            --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED
