on:
  push:
    branches: [ '**' ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  build:
    name: Build OAS Stub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.7.0
      - name: Build
        run: ./gradlew clean build
      - name: Publish to maven local
        run: ./gradlew publishToMavenLocal
      - name: Build example
        run: mvn package
        working-directory: examples
  snapshot-publish:
    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/main' }}
    name: SNAPSHOT publish
    uses: ./.github/workflows/publish.yml
    secrets:
      password: ${{ secrets.GPG_PASS_PHRASE }}
      key: ${{ secrets.GPG_SECRET_KEY }}
      mavenUsername: ${{ secrets.OSSRHUSERNAME }}
      mavenPassword: ${{ secrets.OSSRHPASSWORD }}
    with:
      repository: ${{ vars.SNAPSHOT_REPOSITORY }}
