on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
      repository:
        required: true
        type: string
    secrets:
      password:
        required: true
      key:
        required: true
      mavenUsername:
        required: false
      mavenPassword:
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install GPG secret key
        id: install-secret-key
        run: |
          gpg --version
          cat <(echo -e "${{ secrets.key }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format=long
          gpg --list-keys --keyid-format=long
      - name: Compute keyId
        id: compute-key-id
        run: |
          keyId=`gpg --list-keys --keyid-format short --with-colons | awk -F: '/^pub/ {print substr($5, 9, 16)}'`
          echo $keyId
          echo "GPG_KEY_ID=$keyId" >> "$GITHUB_OUTPUT"
      - name: Setup publish.priperties
        run: |
          echo >> publish.properties
          echo "signing.keyId=${{ steps.compute-key-id.outputs.GPG_KEY_ID }}" >> publish.properties
          echo "signing.key=${{ secrets.key }}" >> publish.properties
          echo "deployment.repository=${{ inputs.repository }}" >> publish.properties
      - name: Setup version property
        if: inputs.version != ''
        run: |
          content=`cat gradle.properties | sed -E 's/version=.+/version=${{ inputs.version }}/'`
          echo "$content" > gradle.properties
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew build -x test
      - name: Publish
        run: ./gradlew publish -Psigning.password=${{ secrets.password }} -Pdeployment.username=${{secrets.mavenUsername }} -Pdeployment.password=${{ secrets.mavenPassword }}
      - name: OSSRH Staging API call
        run: |
          bearer=$(echo "${{ secrets.mavenUsername }}:${{ secrets.mavenPassword }}" | base64)
          version=$(cat gradle.properties | grep 'version' | sed -E 's/version=(.+)/\1/')
          curl -X 'POST' \
            "https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/io.github.ktakashi?publishing_type=user_managed&deployment_name=oas-stub-$version" \
            -H 'accept: */*' \
            -H "Authorization: Bearer $bearer"